<a href="https://colab.research.google.com/github/ahasanulhossain07-del/Deep-Learning-Book/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [6]:
df.shape

(569, 33)

In [7]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [8]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [9]:
X_train,X_test,y_train,y_test=train_test_split(
    df.iloc[:,1:],df.iloc[:,0],test_size=0.2
)

In [10]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
X_train

array([[-0.69980547, -0.47099758, -0.72483305, ..., -0.07081546,
        -0.52102763, -0.69206988],
       [ 0.05655324, -1.34843192,  0.01797446, ..., -0.08904801,
         0.25145161, -1.24194976],
       [-0.18214551, -0.07001953, -0.16574854, ...,  0.46704477,
        -0.37283774, -0.37609013],
       ...,
       [-0.51862449,  0.71542572, -0.50944803, ..., -0.49563387,
        -1.00028006,  0.37281944],
       [-1.21919096, -0.26579117, -1.14477134, ..., -0.23490841,
        -0.45481513,  1.73437567],
       [-0.42084427,  1.09753422, -0.39113208, ...,  0.86664149,
         0.75750433,  1.03160236]])

In [12]:
y_train

187    B
225    B
396    B
91     M
350    B
      ..
46     B
281    B
163    B
176    B
64     M
Name: diagnosis, Length: 455, dtype: object

In [13]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [16]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [29]:
class MySimpleNN():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()

    return loss

In [30]:
learning_rate=0.1
epochs=25

In [31]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.9099793025534133
Epoch: 2, Loss: 3.7905431235720206
Epoch: 3, Loss: 3.6652432661194174
Epoch: 4, Loss: 3.534942042894568
Epoch: 5, Loss: 3.3987292148913055
Epoch: 6, Loss: 3.2619929217623693
Epoch: 7, Loss: 3.125420768287917
Epoch: 8, Loss: 2.9822726632373144
Epoch: 9, Loss: 2.838887634506625
Epoch: 10, Loss: 2.6904482087718784
Epoch: 11, Loss: 2.534498528921717
Epoch: 12, Loss: 2.3726764327835332
Epoch: 13, Loss: 2.2117213610632445
Epoch: 14, Loss: 2.0417645785907363
Epoch: 15, Loss: 1.8699916829591468
Epoch: 16, Loss: 1.7055553398382375
Epoch: 17, Loss: 1.550234341593732
Epoch: 18, Loss: 1.4072324112637316
Epoch: 19, Loss: 1.2762627483847846
Epoch: 20, Loss: 1.1629090104783633
Epoch: 21, Loss: 1.0683255014647959
Epoch: 22, Loss: 0.9924948795009269
Epoch: 23, Loss: 0.9341225574398586
Epoch: 24, Loss: 0.8907794738338628
Epoch: 25, Loss: 0.859312195293131

In [32]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.9).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"Accuracy:{accuracy.item()}")

Accuracy:0.6015697121620178